name: checks

on:
  - push

jobs:
  static_analysis:
    name: Static analysis

    runs-on: ubuntu-latest

    env:
      COMPOSER_NO_INTERACTION: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - run: composer install --ansi --no-progress --prefer-dist

      - name: Run PHPStan
        run: composer run phpstan

  tests:
    name: PHP ${{ matrix.php }} tests on ${{ matrix.os }}

    needs:
      - static_analysis

    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
        php:
          - '8.4'

      fail-fast: false

    runs-on: ${{ matrix.os }}

    env:
      COMPOSER_NO_INTERACTION: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer install --ansi --no-progress --prefer-dist

      - name: Run tests
        run: composer run test

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: tests/output
